apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: domain-pending-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-job
              image: curlimages/curl
              args:
                - /bin/sh
                - -c
                - "curl -X POST http://domain-toolkit:8000/cron/domain-pending"
