apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domainverificationattempts.acme.com
spec:
  group: acme.com
  names:
    kind: DomainVerificationAttempt
    listKind: DomainVerificationAttemptList
    plural: domainverificationattempts
    singular: domainverificationattempt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                domainName:
                  type: string
                userId:
                  type: string
                txtRecord:
                  type: string
                txtDomain:
                  type: string
                verificationStatus:
                  type: string
                  enum: [Pending, Verified, Failed]
