kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingressroute-role
rules:
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingressroute-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingressroute-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
